---
title: "Function Vignettes"
author: "Ben Estes"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}

# --- Quiz1 Functions ---

# Finds the mean, variance, and sd for a vector


func1 <- function(x){

  a <- (1/length(x))*sum(x)
  b <- (1/length(x))*sum((x-a)^2)
  c <- sqrt(b)

  ans <- list(mean=a,var=b,sd=c)
  return(ans)
}

 x <- scan(url("http://www.stat.umn.edu/geyer/3701/data/q1p1.txt"))

 func1(x)
 
# Finds the mean, variance, and sd for a vector, has a GIEMO check as well
func2 <- function(x){

  for(i in 1:length(x))
  {
    if(is.finite(x[i])==FALSE)
    {
      return("Error: Non-numeric input")
    }
  }

  a <- (1/length(x))*sum(x)
  b <- (1/length(x))*sum((x-a)^2)
  c <- sqrt(b)

  ans <- list(mean=a,var=b,sd=c)
  return(ans)
}

x <- scan(url("http://www.stat.umn.edu/geyer/3701/data/q1p1.txt"))
func1(x)




#Finds the mle for a dataset given a gamma distribution
mle1 <- function(x)
{
  alpha <- pi
  interval <- mean(x)+c(-1,1)*3*sd(x)
  interval <- pmax(mean(x)/1e3,interval)

  log1 <- function(alpha,x)
  {
    sum(dgamma(x,shape=alpha,log=TRUE))
  }

  return(optimize(log1,maximum = TRUE, interval,x = x)$maximum)
}

x <- scan(url("http://www.stat.umn.edu/geyer/3701/data/q1p3.txt"))
mle1(x)
```



```{r}

# --- HW1 Functions ---

#Finds the mean, variance, and sd for a vector with an uneven probability distribution.
func4 <- function(x,p){

  a <- sum(x*p)
  b <- sum(p*(x-a)^2)
  c <- sqrt(b)

  ans <- list(mean=a,var=b,sd=c)
  return(ans)
}
d <- read.table(url("http://www.stat.umn.edu/geyer/3701/data/q1p4.txt"),
header = TRUE)
func4(d$x,d$p)



# Finds the mean, variance, and sd for a vector with an uneven probability distribution, with a GIEMO check
func5 <- function(x,p){

  for(i in 1:length(x))
  {
    if((is.finite(x[i])==FALSE)|(is.finite(p[i])==FALSE)|(isTRUE(all.equal(sum(p),1))==FALSE)|((p[i]<0)==TRUE))
    {
      return("Error: Non-standard inputs")
    }
  }

  a <- sum(x*p)
  b <- sum(p*(x-a)^2)
  c <- sqrt(b)

  ans <- list(mean=a,var=b,sd=c)
  return(ans)
}

 d <- read.table(url("http://www.stat.umn.edu/geyer/3701/data/q1p4.txt"),header = TRUE)
 func4(d$x,d$p)

 
 
#Finds the MLE for a generic data distribution.
mle2 <- function(x,interval,FUN)
{
  theta <- pi

  log1 <- function(theta,x)
  {
    sum(FUN(theta,x))
  }

  return(optimize(log1,maximum = TRUE, interval,x=x)$maximum)
}

gamma.FUN <- function(theta, x) dgamma(x, shape = theta, log = TRUE)
cauchy.FUN <- function(theta, x) dcauchy(x, location = theta, log = TRUE)

xgam <- scan(url("http://www.stat.umn.edu/geyer/3701/data/q1p3.txt"))
xcau <- scan(url("http://www.stat.umn.edu/geyer/3701/data/q1p7c.txt"))

interval <- 1:100

mle2(xgam,interval,gamma.FUN)
mle2(xcau,interval,cauchy.FUN)

```


```{r}
# --- Quiz2 Functions ---

# A matrix calculator that calculates x^t(A^-1)x, has GIEMO checks for non-numeric and non compatible dims.
matCalc <- function(A,x)
{
  if((sum(is.finite(A))!=sum(is.finite(A)|TRUE))|(sum(is.finite(x))!=sum(is.finite(x)|TRUE)))
  {
    return("Non numeric arguments")
  }

  if((ncol(A)!=nrow(A))|(length(x)!=nrow(A)))
  {
    return("Non-compatible dimmensions")
  }

  A_i <- solve(A)
  result <- x%*%A_i%*%x
  return(result)
}
 load(url("http://www.stat.umn.edu/geyer/3701/data/q2p1.rda"))
 matCalc(a,x)


# A matrix calculator that calculates x^t(A^-1)x, has GIEMO checks for non-numeric and non compatible dims.
# Acts as an operator rather than a function

"%matCalcOp%" <- function(A,x)
{
  if((sum(is.finite(A))!=sum(is.finite(A)|TRUE))|(sum(is.finite(x))!=sum(is.finite(x)|TRUE)))
  {
    return("Non numeric arguments")
  }

  if((ncol(A)!=nrow(A))|(length(x)!=nrow(A)))
  {
    return("Non-compatible dimmensions")
  }

  A_i <- solve(A)
  result <- x%*%A_i%*%x
  return(result)
}

load(url("http://www.stat.umn.edu/geyer/3701/data/q2p1.rda"))
 a%matCalcOp%x


# Standardizes all the columns of a matrix
mat.Standard <- function(A)
{
  if(nrow(A)==1)
  {
    return("Matrix with one row cannot be standardized")
  }

  for (i in 1:ncol(A))
  {
    A[,i] <- (A[,i]-mean(A[,i]))/sd(A[,i])
  }

  return(A)
}

 load(url("http://www.stat.umn.edu/geyer/3701/data/q2p3.rda"))
 mat.Standard(a)



# --- HW2 Functions ---

#' A function that standardizes a single vector, designed for use in the apply function. Also has GIEMO
vect.Standardize <- function(v)
{
  if(length(v)==1){return("Vectors of length one cannot be standardized")}
  (v-mean(v))/sd(v)
}
load(url("http://www.stat.umn.edu/geyer/3701/data/q2p3.rda"))
apply(a,2,vect.Standardize)


#' A rudimentary version of the apply function.

myapply <- function(X,MARGIN,FUN,...)
{
  FUN <- match.fun(FUN)

  if(MARGIN!=1&&MARGIN!=2)
  {
    return("Error: MARGIN must be 1 or 2")
  }

  if(MARGIN==1)
  {
    new <- FUN(X[1,],...)
    for (i in 2:nrow(X)) {new <-cbind(new,FUN(X[i,],...))}
  }

  if(MARGIN==2)
  {
    new <- FUN(X[,1],...)
    for (i in 2:ncol(X)) {new <- cbind(new,FUN(X[,i],...))}
  }

  return(new)
}
fred <- array(1:6,c(3,2))
apply(fred,1,mean)
myapply(fred,1,mean)
```

```{r}
#' Basic wrapper function for ggplot

plotMyData<-function(x)
{
  x%>% ggplot2::ggplot()+ggplot2::aes(x=x, y=p)+ggplot2::geom_point()
}
```








```
